### ISSUE TITLE
The "select_thread" endpoint only allows users to select threads they have personally submitted.

### ISSUE THREAD

**Issue by ccampo133** [millionairemakers/millionairemakers#3]
If a moderator wanted to select a thread for the drawing process, he would have had to submitted that thread on Reddit himself for it to appear in the "select thread" dropdown. A better alternative would be to present a list of threads from the r/millionairemakers subreddit.

**Comment by minlite** [comment]
This has been addressed by adding a field that lets the user input a custom post id.
